--- 
- african
- tradamerican
- argentine
- asianfusion
- bbq
- basque
- belgian
- bistros
- brasseries
- brazilian
- breakfast_brunch
- british
- buffets
- burgers
- cafes
- cajun
- cambodian
- caribbean
- chinese
- creperies
- cuban
- delis
- diners
- ethiopian
- hotdogs
- filipino
- fishnchips
- fondue
- foodstands
- french
- gastropubs
- german
- gluten_free
- greek
- halal
- hawaiian
- himalayan
- hotdog
- hungarian
- indpak
- indonesian
- irish
- italian
- japanese
- korean
- kosher
- latin
- lebanese
- raw_food
- malaysian
- mediterranean
- mexican
- mideastern
- modern_european
- mongolian
- moroccan
- pakistani
- persian
- peruvian
- pizza
- polish
- portuguese
- russian
- sandwiches
- scandinavian
- seafood
- singaporean
- soulfood
- soup
- spanish
- steak
- sushi
- taiwanese
- tapas
- tapasmallplates
- tex-mex
- thai
- turkish
- vegan
- vegetarian
- vietnamese
